[sources.debian]
base_url = "http://ftp.de.debian.org"
distribution = "debian"
components = ["bookworm", "main"]

[sources.debian.packages.kodi]
deps = ["kodi-bin>=0", "kodi-data>=0"]

[sources.scenebuilder]
repository = "gluonhq/scenebuilder"

[sources.scenebuilder.packages."SceneBuilder-*.deb"]
name = "scenebuilder"

[sources.gitkraken]
url = "https://release.axocdn.com/linux/gitkraken-amd64.deb"
not_deps = ["musl"]

[sources.discord]
url = "https://discord.com/api/download?platform=linux&format=deb"

[sources.unity]
base_url = "https://hub-dist.unity3d.com/artifactory/"
distribution = "hub-debian-prod-local"
components = ["stable", "main"]

[sources.obsidian]
repository = "obsidianmd/obsidian-releases"

[sources.obsidian."obsidian-*-amd64.deb"]
name = "obsidian"

[sources.figma-linux]
repository = "Figma-Linux/figma-linux"

[sources.figma-linux."figma-linux_*_linux_amd64.deb"]
name = "figma-linux"

[sources.brave-browser]
repository = "brave/brave-browser"

[sources.brave-browser.packages."*_amd64.deb"]
name = "brave-browser"

[sources.spotify]
base_url = "http://repository.spotify.com"
distribution = ""
components = ["stable", "non-free"]

# configure packages
[sources.slack]
base_url = "https://packagecloud.io/slacktechnologies/slack/"
distribution = "debian"
components = ["jessie", "main"]

[sources.llvm19]
base_url = "https://apt.llvm.org/"
distribution = "bullseye"
components = ["llvm-toolchain-bullseye", "main"]

[sources.llvm19.packages.clang-19]
name = "clang19"

[sources.llvm19.packages.clang-format-19]
name = "clang-format19"

[sources.llvm19.packages.libclang-19-dev]
name = "libclang19-dev"

[sources.llvm19.packages.libclang-common-19-dev]
name = "clang19-headers"

[packages.code]
url = "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

[packages.code-insiders]
url = "https://code.visualstudio.com/sha/download?build=insider&os=linux-deb-x64"
